import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const workflowUrl = new URL('../../../.github/workflows/dsh-upstream-update.yml', import.meta.url)
const validationUrl = new URL('../../../.github/workflows/dsh-candidate-validation.yml', import.meta.url)
const productionUrl = new URL('../../../.github/workflows/production-publish.yml', import.meta.url)
const dockerUrl = new URL('../../../.github/workflows/docker.yaml', import.meta.url)
const gotifyWorkflow = 'yjrszcq/github-workflows/.github/workflows/gotify-notify.yml@c4c7fe9e17854cd4962913ac2792513eab0be988'

test('upstream workflow discovers candidates without production credentials', async () => {
  const workflow = await readFile(workflowUrl, 'utf8')
  assert.match(workflow, /schedule:/)
  assert.match(workflow, /workflow_dispatch:/)
  assert.match(workflow, /contents: write/)
  assert.match(workflow, /pull-requests: write/)
  assert.match(workflow, /supported-target\.mjs" advance/)
  assert.match(workflow, /trusted-platform/)
  assert.match(workflow, /node "\$trusted_platform\/tools\/supported-target\.mjs"/)
  assert.match(workflow, /git merge --no-edit/)
  assert.match(workflow, /replace_closed=true/)
  assert.match(workflow, /git push --force-with-lease/)
  assert.match(workflow, /git push origin/)
  assert.match(workflow, /chore\(dsh\): validate/)
  assert.doesNotMatch(workflow, /DSH_RELEASE_PRIVATE_KEY|DSH_RECOVERY|DOCKER_TOKEN/)
})

test('upstream workflow calls only the pinned reusable Gotify interface', async () => {
  const workflow = await readFile(workflowUrl, 'utf8')
  assert.equal(workflow.split(gotifyWorkflow).length - 1, 3)
  assert.match(workflow, /gotify_url: \$\{\{ secrets\.GOTIFY_URL \}\}/)
  assert.match(workflow, /gotify_token: \$\{\{ secrets\.GOTIFY_TOKEN \}\}/)
  assert.doesNotMatch(workflow, /secrets: inherit/)
})

test('candidate validation is secret-free and exercises the complete current Environment', async () => {
  const workflow = await readFile(validationUrl, 'utf8')
  assert.match(workflow, /workflow_call:/)
  assert.match(workflow, /pull_request:/)
  assert.match(workflow, /permissions:\n  contents: read/)
  assert.match(workflow, /supported-target\.mjs validate/)
  assert.match(workflow, /dist\.integrity/)
  assert.match(workflow, /npm test --prefix container\/control-plane\/services\/gateway/)
  assert.match(workflow, /npm test --prefix container\/platform/)
  assert.match(workflow, /npm ci --omit=dev --ignore-scripts --prefix container\/control-plane\/services\/management/)
  assert.match(workflow, /container-smoke\.sh/)
  assert.match(workflow, /devtools-smoke\.sh/)
  assert.doesNotMatch(workflow, /secrets\.|DSH_RELEASE_PRIVATE_KEY|DSH_RECOVERY|DOCKER_TOKEN/)
})

test('discovery run reports candidate status and distinct validation notifications', async () => {
  const workflow = await readFile(workflowUrl, 'utf8')
  assert.match(workflow, /uses: \.\/\.github\/workflows\/dsh-candidate-validation\.yml/)
  assert.match(workflow, /statuses: write/)
  assert.match(workflow, /DSH candidate Runtime/)
  assert.match(workflow, /notify-validation-passed:/)
  assert.match(workflow, /notify-validation-failed:/)
})

test('production publication owns signing, advances an append-only channel, and releases only Environment versions', async () => {
  const workflow = await readFile(productionUrl, 'utf8')
  assert.match(workflow, /branches:\n      - main/)
  assert.match(workflow, /release\/supported-target\.json/)
  assert.match(workflow, /release\/official-dsh-policy\.json/)
  assert.match(workflow, /environment: production-release/)
  assert.match(workflow, /if: github\.ref == 'refs\/heads\/main'/)
  assert.match(workflow, /DSH_RELEASE_PRIVATE_KEY/)
  assert.match(workflow, /prepare-release\.mjs/)
  assert.match(workflow, /environment-release\.mjs/)
  assert.match(workflow, /npm ci --omit=dev --ignore-scripts --prefix container\/control-plane\/services\/management/)
  assert.match(workflow, /refs\/heads\/release-channel/)
  assert.match(workflow, /sequence=1/)
  assert.match(workflow, /current_sequence \+ 1/)
  assert.match(workflow, /release-channel\/targets\/\$\{TARGET_SEQUENCE\}/)
  assert.match(workflow, /test ! -e "\$target"/)
  assert.match(workflow, /tag="v\$\{ENVIRONMENT_VERSION\}"/)
  assert.match(workflow, /--title "\$ENVIRONMENT_TAG"/)
  assert.doesNotMatch(workflow, /--title "DSH Docker Environment/)
  assert.match(workflow, /cmp "\$RUNNER_TEMP\/environment-release\.json"/)
  assert.match(workflow, /--draft/)
  assert.match(workflow, /--draft=false/)
  assert.match(workflow, /--latest/)
  assert.match(workflow, /--json isDraft/)
  assert.doesNotMatch(workflow, /uses: \.\/\.github\/workflows\/docker\.yaml/)
  assert.doesNotMatch(workflow, /environment: production-image|DOCKER_TOKEN/)
  assert.equal(workflow.split(gotifyWorkflow).length - 1, 1)
  assert.match(workflow, /notify-failed:[\s\S]*if: \$\{\{ failure\(\) \}\}[\s\S]*DSH 正式发布失败/)
  assert.doesNotMatch(workflow, /platform-\$\{TARGET_SEQUENCE\}|DSH Platform \$\{TARGET_SEQUENCE\}/)
  assert.doesNotMatch(workflow, /RECOVERY_PRIVATE|secrets: inherit/)
})

test('Docker publication consumes one signed channel target and mirrors only standard images to GHCR', async () => {
  const workflow = await readFile(dockerUrl, 'utf8')
  assert.match(workflow, /workflow_run:/)
  assert.match(workflow, /Publish Supported Platform Target/)
  assert.match(workflow, /github\.event\.workflow_run\.conclusion == 'success'/)
  assert.match(workflow, /github\.event\.workflow_run\.head_sha/)
  assert.match(workflow, /environment: production-image/)
  assert.match(workflow, /contents: read\n      packages: write/)
  assert.match(workflow, /git -C channel log --format=%H -- channel\.json/)
  assert.match(workflow, /No signed release-channel target matches source commit/)
  assert.match(workflow, /latestSupportedDsh/)
  assert.match(workflow, /channel\/targets\/\$sequence/)
  assert.match(workflow, /verify-image-release\.mjs/)
  assert.match(workflow, /PLATFORM_REVISION=\$\{\{ steps\.channel\.outputs\.source_commit \}\}/)
  assert.match(workflow, /ENVIRONMENT_VERSION=\$\{\{ steps\.signed-target\.outputs\.environment_version \}\}/)
  assert.match(workflow, /TARGET_SEQUENCE=\$\{\{ steps\.signed-target\.outputs\.sequence \}\}/)
  assert.match(workflow, /npm ci --omit=dev --ignore-scripts --prefix container\/control-plane\/services\/management/)
  assert.match(workflow, /DOCKERHUB_IMAGE: szcq\/deepseek-harness/)
  assert.match(workflow, /GHCR_IMAGE: ghcr\.io\/\$\{\{ github\.repository \}\}/)
  assert.match(workflow, /\$\{GHCR_IMAGE\}:\$\{ENVIRONMENT_VERSION\}/)
  assert.match(workflow, /\$\{GHCR_IMAGE\}:\$\{major\}\.\$\{minor\}/)
  assert.match(workflow, /\$\{GHCR_IMAGE\}:dsh-\$\{DSH_VERSION\}/)
  assert.match(workflow, /\$\{DOCKERHUB_IMAGE\}:\$\{DSH_VERSION\}-devtools/)
  assert.equal(workflow.split(gotifyWorkflow).length - 1, 2)
  assert.match(workflow, /notify-failed:[\s\S]*if: \$\{\{ failure\(\) \}\}[\s\S]*DSH 镜像发布失败/)
  assert.doesNotMatch(workflow, /\$\{GHCR_IMAGE\}:[^\n]*devtools/)
  assert.doesNotMatch(workflow, /workflow_call:|gh release|DSH_RELEASE_PRIVATE_KEY|prepare-release\.mjs/)
})
